#!/usr/bin/env bash

i3c="${HOME}/.config/i3/i3c"

#data_from i3c
BAR_X=$(${i3c} dzen2-bar-x ${1})
BAR_WIDTH=$(${i3c} dzen2-bar-width ${1})

BAR_FONT="-*-fixed-medium-*-*-*-12-*-*-*-*-*-*-*"
BAR_FG="#ffffff"
BAR_BG="#222222"
BAR_MARGIN=10

while sleep 1; do
    # Left block
    left=""
    left="${left}$(${i3c} dzen2-bar-workspaces ${1})"

    ## add margin for left side
    printf "^pa(${BAR_MARGIN})"
    printf "${left}"

    # Centre block
    centre=""
    centre="${centre}$(date +%H:%M:%S)"

    ## find the offset for the centre block
    width=$(dzen2-textwidth "${BAR_FONT}" "${centre}")
    offset=$(( ( ${BAR_WIDTH} - ${width} ) / 2 ))
    printf "^pa(${offset})"
    printf "${centre}"

    # Right block
    right=""
    right="${right}"
    right="${right}$(date +%Y-%m-%d)"

    ## find the offset for the right block
    width=$(dzen2-textwidth "${BAR_FONT}" "${right}")
    offset=$((${BAR_WIDTH} - ${width} - ${BAR_MARGIN}))
    printf "^pa(${offset})"
    printf "${right}"

    printf "\n"
done | dzen2 -dock \
             -ta l \
             -x ${BAR_X} \
             -w ${BAR_WIDTH} \
             -fg ${BAR_FG} \
             -bg ${BAR_BG} \
             -fn ${BAR_FONT}
